### ISSUE TITLE
Any other jurisdictions running Checkbook?

### ISSUE THREAD

**Issue by jqnatividad** [NYCComptroller/Checkbook#51]
Is there a showcase site of other cities running it?

**Comment by jqnatividad** [comment]
Thanks for assigning Q label! 

Also ccing @kfogel @ecs-hk @bruleyii @rkalidindi who at first glance, seem to be third-party contributors to the project.

**Comment by kfogel** [comment]
Hi, @jqnatividad.  There has been at least one re-deployment, by Williamson County, Texas:

http://wilco.mygovcenter.com/spending_landing/yeartype/B/year/117?expandBottomCont=true

(I've been in contact with them about it a bit; happy to answer any questions we can.)

By the way, @bruleyii and @rkalidindi work for REI Systems, the original developer and current primary maintainer of Checkbook (New York City contracted with REI Systems to build, deploy, and maintain Checkbook), and I believe @ecs-hk works for Mo'mix Solutions, who did the port for Williamson County.

**Comment by jqnatividad** [comment]
Thanks @kfogel for the info!

Are there any bulk download options available for getting data?  Also, I noticed that some queries are very expensive, what caching strategy is being used to make Checkbook faster?

Thanks!
Joel

**Comment by alex-perfilov-reisys** [comment]
we're using [memcached](https://memcached.org) for Drupal side and switched PostgreSQL to [greenplum](http://greenplum.org) to improve performance so far
